// Mock data for MediCore Nexus
import { User, Patient, Appointment, MedicalRecord, Prescription, LabTest, Invoice, Organization, Message, AuditLog } from './types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'admin@medicore.com',
    password: 'admin123',
    role: 'super_admin',
    firstName: 'Sarah',
    lastName: 'Administrator',
    phone: '+1-555-0100',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    department: 'Administration',
  },
  {
    id: 'u2',
    email: 'dr.smith@medicore.com',
    password: 'doctor123',
    role: 'doctor',
    firstName: 'John',
    lastName: 'Smith',
    phone: '+1-555-0101',
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    specialization: 'Internal Medicine',
    department: 'Medicine',
    licenseNumber: 'MD-12345',
  },
  {
    id: 'u3',
    email: 'dr.johnson@medicore.com',
    password: 'doctor123',
    role: 'doctor',
    firstName: 'Emily',
    lastName: 'Johnson',
    phone: '+1-555-0102',
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    specialization: 'Cardiology',
    department: 'Cardiology',
    licenseNumber: 'MD-12346',
  },
  {
    id: 'u4',
    email: 'lab.tech@medicore.com',
    password: 'lab123',
    role: 'lab_tech',
    firstName: 'Michael',
    lastName: 'Chen',
    phone: '+1-555-0103',
    isActive: true,
    createdAt: '2024-01-03T00:00:00Z',
    department: 'Laboratory',
    licenseNumber: 'MLT-789',
  },
  {
    id: 'u5',
    email: 'patient@example.com',
    password: 'patient123',
    role: 'patient',
    firstName: 'David',
    lastName: 'Wilson',
    phone: '+1-555-0104',
    isActive: true,
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    id: 'u6',
    email: 'receptionist@medicore.com',
    password: 'reception123',
    role: 'receptionist',
    firstName: 'Lisa',
    lastName: 'Martinez',
    phone: '+1-555-0105',
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    department: 'Front Desk',
  },
  {
    id: 'u7',
    email: 'nurse@medicore.com',
    password: 'nurse123',
    role: 'nurse',
    firstName: 'Jennifer',
    lastName: 'Davis',
    phone: '+1-555-0106',
    isActive: true,
    createdAt: '2024-01-06T00:00:00Z',
    department: 'Nursing',
    licenseNumber: 'RN-456',
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    userId: 'u5',
    firstName: 'David',
    lastName: 'Wilson',
    dateOfBirth: '1985-03-15',
    gender: 'male',
    email: 'patient@example.com',
    phone: '+1-555-0104',
    address: '123 Main St, Springfield, IL 62701',
    emergencyContact: {
      name: 'Jane Wilson',
      phone: '+1-555-0199',
      relationship: 'Spouse',
    },
    insurance: {
      provider: 'Blue Cross Blue Shield',
      policyNumber: 'BCBS-123456',
      groupNumber: 'GRP-789',
    },
    allergies: ['Penicillin', 'Peanuts'],
    medications: ['Lisinopril 10mg'],
    conditions: ['Hypertension', 'Type 2 Diabetes'],
    bloodType: 'A+',
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    id: 'p2',
    firstName: 'Mary',
    lastName: 'Thompson',
    dateOfBirth: '1990-07-22',
    gender: 'female',
    email: 'mary.thompson@example.com',
    phone: '+1-555-0107',
    address: '456 Oak Ave, Springfield, IL 62702',
    emergencyContact: {
      name: 'Robert Thompson',
      phone: '+1-555-0198',
      relationship: 'Father',
    },
    insurance: {
      provider: 'Aetna',
      policyNumber: 'AET-654321',
      groupNumber: 'GRP-456',
    },
    allergies: ['Sulfa drugs'],
    medications: [],
    conditions: ['Asthma'],
    bloodType: 'O-',
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'p3',
    firstName: 'Robert',
    lastName: 'Brown',
    dateOfBirth: '1975-11-30',
    gender: 'male',
    email: 'robert.brown@example.com',
    phone: '+1-555-0108',
    address: '789 Elm St, Springfield, IL 62703',
    emergencyContact: {
      name: 'Susan Brown',
      phone: '+1-555-0197',
      relationship: 'Spouse',
    },
    allergies: [],
    medications: ['Metformin 500mg', 'Atorvastatin 20mg'],
    conditions: ['Type 2 Diabetes', 'Hyperlipidemia'],
    bloodType: 'B+',
    createdAt: '2024-03-05T00:00:00Z',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    patientId: 'p1',
    doctorId: 'u2',
    date: '2025-10-15',
    time: '09:00',
    duration: 30,
    type: 'Follow-up',
    status: 'scheduled',
    reason: 'Blood pressure check',
    createdAt: '2025-10-10T00:00:00Z',
    createdBy: 'u6',
  },
  {
    id: 'a2',
    patientId: 'p1',
    doctorId: 'u2',
    date: '2025-10-15',
    time: '14:00',
    duration: 30,
    type: 'Consultation',
    status: 'confirmed',
    reason: 'Diabetes management review',
    createdAt: '2025-10-10T00:00:00Z',
    createdBy: 'u6',
  },
  {
    id: 'a3',
    patientId: 'p2',
    doctorId: 'u3',
    date: '2025-10-15',
    time: '10:30',
    duration: 45,
    type: 'Initial Consultation',
    status: 'scheduled',
    reason: 'Chest pain evaluation',
    createdAt: '2025-10-11T00:00:00Z',
    createdBy: 'u6',
  },
  {
    id: 'a4',
    patientId: 'p3',
    doctorId: 'u2',
    date: '2025-10-16',
    time: '11:00',
    duration: 30,
    type: 'Follow-up',
    status: 'scheduled',
    reason: 'Lab results review',
    createdAt: '2025-10-12T00:00:00Z',
    createdBy: 'u6',
  },
  {
    id: 'a5',
    patientId: 'p1',
    doctorId: 'u2',
    date: '2025-10-08',
    time: '09:00',
    duration: 30,
    type: 'Follow-up',
    status: 'completed',
    reason: 'Routine checkup',
    consultationNotes: 'Patient is responding well to current medication. BP: 125/80. Continue current treatment.',
    createdAt: '2025-10-01T00:00:00Z',
    createdBy: 'u6',
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'mr1',
    patientId: 'p1',
    appointmentId: 'a5',
    doctorId: 'u2',
    date: '2025-10-08',
    type: 'soap-note',
    chiefComplaint: 'Follow-up for hypertension and diabetes',
    subjective: 'Patient reports feeling well. No new symptoms. Compliance with medications is good.',
    objective: 'BP: 125/80 mmHg, HR: 72 bpm, Weight: 180 lbs, Blood glucose: 110 mg/dL',
    assessment: 'Hypertension - well controlled, Type 2 Diabetes - stable',
    plan: 'Continue current medications. Schedule lab work in 3 months. Follow-up in 3 months.',
    vitalSigns: {
      temperature: 98.6,
      bloodPressure: '125/80',
      heartRate: 72,
      respiratoryRate: 16,
      oxygenSaturation: 98,
      weight: 180,
      height: 70,
    },
    createdAt: '2025-10-08T09:30:00Z',
    updatedAt: '2025-10-08T09:30:00Z',
  },
];

export const mockPrescriptions: Prescription[] = [
  {
    id: 'rx1',
    patientId: 'p1',
    doctorId: 'u2',
    medication: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily',
    duration: '90 days',
    instructions: 'Take in the morning with water',
    refills: 3,
    status: 'active',
    startDate: '2025-01-15',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'rx2',
    patientId: 'p1',
    doctorId: 'u2',
    medication: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice daily',
    duration: '90 days',
    instructions: 'Take with meals',
    refills: 3,
    status: 'active',
    startDate: '2025-01-15',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'rx3',
    patientId: 'p3',
    doctorId: 'u2',
    medication: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once daily at bedtime',
    duration: '90 days',
    instructions: 'Take at bedtime',
    refills: 3,
    status: 'active',
    startDate: '2025-03-10',
    createdAt: '2025-03-10T00:00:00Z',
  },
];

export const mockLabTests: LabTest[] = [
  {
    id: 'lt1',
    patientId: 'p3',
    orderedBy: 'u2',
    assignedTo: 'u4',
    type: 'Lipid Panel',
    category: 'Chemistry',
    priority: 'routine',
    status: 'completed',
    orderedDate: '2025-10-10',
    completedDate: '2025-10-11',
    results: [
      { parameter: 'Total Cholesterol', value: '245', unit: 'mg/dL', normalRange: '< 200', isAbnormal: true },
      { parameter: 'LDL Cholesterol', value: '155', unit: 'mg/dL', normalRange: '< 100', isAbnormal: true },
      { parameter: 'HDL Cholesterol', value: '45', unit: 'mg/dL', normalRange: '> 40', isAbnormal: false },
      { parameter: 'Triglycerides', value: '225', unit: 'mg/dL', normalRange: '< 150', isAbnormal: true },
    ],
    interpretation: 'Elevated cholesterol and triglycerides. Continue statin therapy and recommend dietary modifications.',
    criticalFlag: false,
    createdAt: '2025-10-10T00:00:00Z',
  },
  {
    id: 'lt2',
    patientId: 'p1',
    orderedBy: 'u2',
    assignedTo: 'u4',
    type: 'HbA1c',
    category: 'Chemistry',
    priority: 'routine',
    status: 'in-progress',
    orderedDate: '2025-10-14',
    createdAt: '2025-10-14T00:00:00Z',
  },
  {
    id: 'lt3',
    patientId: 'p2',
    orderedBy: 'u3',
    type: 'Cardiac Enzymes',
    category: 'Chemistry',
    priority: 'stat',
    status: 'pending',
    orderedDate: '2025-10-15',
    createdAt: '2025-10-15T00:00:00Z',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    patientId: 'p1',
    appointmentId: 'a5',
    date: '2025-10-08',
    dueDate: '2025-11-08',
    items: [
      { description: 'Office Visit - Follow-up', code: '99213', quantity: 1, unitPrice: 150, total: 150 },
      { description: 'Blood Pressure Check', code: '93000', quantity: 1, unitPrice: 25, total: 25 },
    ],
    subtotal: 175,
    tax: 0,
    total: 175,
    amountPaid: 175,
    status: 'paid',
    createdAt: '2025-10-08T00:00:00Z',
  },
  {
    id: 'inv2',
    patientId: 'p3',
    date: '2025-10-11',
    dueDate: '2025-11-11',
    items: [
      { description: 'Lipid Panel', code: '80061', quantity: 1, unitPrice: 85, total: 85 },
    ],
    subtotal: 85,
    tax: 0,
    total: 85,
    amountPaid: 0,
    status: 'pending',
    createdAt: '2025-10-11T00:00:00Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg1',
    from: 'u2',
    to: 'u5',
    subject: 'Lab Results Available',
    body: 'Your recent lab results are now available. Please log in to the portal to view them. Overall, your numbers look good. Let me know if you have any questions.',
    read: false,
    sentAt: '2025-10-14T10:00:00Z',
  },
  {
    id: 'msg2',
    from: 'u5',
    to: 'u2',
    subject: 'Question about medication',
    body: 'Hi Dr. Smith, I have a question about the timing of my Metformin. Is it okay to take it right before meals or should it be during?',
    read: true,
    sentAt: '2025-10-13T14:30:00Z',
  },
];

export const mockOrganization: Organization = {
  id: 'org1',
  name: 'MediCore Nexus Enterprise',
  locations: [
    {
      id: 'loc1',
      name: 'Main Medical Center',
      address: '100 Healthcare Blvd, Springfield, IL 62701',
      phone: '+1-555-0100',
      hours: {
        monday: { open: '08:00', close: '18:00' },
        tuesday: { open: '08:00', close: '18:00' },
        wednesday: { open: '08:00', close: '18:00' },
        thursday: { open: '08:00', close: '18:00' },
        friday: { open: '08:00', close: '17:00' },
        saturday: { open: '09:00', close: '13:00' },
        sunday: null,
      },
    },
    {
      id: 'loc2',
      name: 'North Clinic',
      address: '250 North Ave, Springfield, IL 62702',
      phone: '+1-555-0200',
      hours: {
        monday: { open: '09:00', close: '17:00' },
        tuesday: { open: '09:00', close: '17:00' },
        wednesday: { open: '09:00', close: '17:00' },
        thursday: { open: '09:00', close: '17:00' },
        friday: { open: '09:00', close: '17:00' },
        saturday: null,
        sunday: null,
      },
    },
  ],
  departments: [
    { id: 'dept1', name: 'Internal Medicine', locationId: 'loc1', rooms: ['101', '102', '103'] },
    { id: 'dept2', name: 'Cardiology', locationId: 'loc1', rooms: ['201', '202'] },
    { id: 'dept3', name: 'Laboratory', locationId: 'loc1', rooms: ['L01', 'L02', 'L03'] },
    { id: 'dept4', name: 'Emergency', locationId: 'loc1', rooms: ['E01', 'E02', 'E03', 'E04'] },
  ],
  appointmentTypes: [
    { id: 'at1', name: 'Initial Consultation', duration: 60, cost: 200 },
    { id: 'at2', name: 'Follow-up Visit', duration: 30, cost: 150 },
    { id: 'at3', name: 'Annual Physical', duration: 45, cost: 250 },
    { id: 'at4', name: 'Sick Visit', duration: 20, cost: 100 },
  ],
  insuranceProviders: [
    'Blue Cross Blue Shield',
    'Aetna',
    'UnitedHealthcare',
    'Cigna',
    'Humana',
    'Medicare',
    'Medicaid',
  ],
};

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit1',
    userId: 'u2',
    action: 'UPDATE',
    resource: 'prescription',
    resourceId: 'rx1',
    details: 'Updated prescription refills from 2 to 3',
    timestamp: '2025-10-14T10:30:00Z',
    ipAddress: '192.168.1.100',
  },
  {
    id: 'audit2',
    userId: 'u4',
    action: 'CREATE',
    resource: 'lab_result',
    resourceId: 'lt1',
    details: 'Completed lipid panel for patient p3',
    timestamp: '2025-10-11T15:45:00Z',
    ipAddress: '192.168.1.105',
  },
  {
    id: 'audit3',
    userId: 'u6',
    action: 'CREATE',
    resource: 'appointment',
    resourceId: 'a3',
    details: 'Scheduled appointment for patient p2',
    timestamp: '2025-10-11T09:00:00Z',
    ipAddress: '192.168.1.110',
  },
];

// Common medications for search
export const commonMedications = [
  { name: 'Lisinopril', commonDosages: ['5mg', '10mg', '20mg', '40mg'] },
  { name: 'Metformin', commonDosages: ['500mg', '850mg', '1000mg'] },
  { name: 'Atorvastatin', commonDosages: ['10mg', '20mg', '40mg', '80mg'] },
  { name: 'Amlodipine', commonDosages: ['2.5mg', '5mg', '10mg'] },
  { name: 'Omeprazole', commonDosages: ['20mg', '40mg'] },
  { name: 'Losartan', commonDosages: ['25mg', '50mg', '100mg'] },
  { name: 'Levothyroxine', commonDosages: ['25mcg', '50mcg', '75mcg', '100mcg'] },
  { name: 'Gabapentin', commonDosages: ['100mg', '300mg', '400mg'] },
  { name: 'Sertraline', commonDosages: ['25mg', '50mg', '100mg'] },
  { name: 'Albuterol', commonDosages: ['90mcg inhaler'] },
];

// Common lab tests
export const commonLabTests = [
  { name: 'Complete Blood Count (CBC)', category: 'Hematology' },
  { name: 'Basic Metabolic Panel', category: 'Chemistry' },
  { name: 'Comprehensive Metabolic Panel', category: 'Chemistry' },
  { name: 'Lipid Panel', category: 'Chemistry' },
  { name: 'HbA1c', category: 'Chemistry' },
  { name: 'TSH', category: 'Chemistry' },
  { name: 'Urinalysis', category: 'Urinalysis' },
  { name: 'Liver Function Tests', category: 'Chemistry' },
  { name: 'Cardiac Enzymes', category: 'Chemistry' },
  { name: 'Vitamin D', category: 'Chemistry' },
  { name: 'PSA', category: 'Chemistry' },
  { name: 'Pregnancy Test', category: 'Immunology' },
];
